spring.application.name=warehouse

# Telegram Bot
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:}
telegram.master.chat-id=${TELEGRAM_MASTER_CHAT_ID:}
telegram.webhook.secret=${TELEGRAM_WEBHOOK_SECRET:}

# Telegram files
telegram.files.how-to-find-video-id=${TELEGRAM_HOW_TO_FIND_VIDEO_ID:}
telegram.files.checklist-photo-id=${TELEGRAM_CHECKLIST_PHOTO_ID:}

# Internal
internal.secret=${INTERNAL_SECRET:dev-secret}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

server.address=0.0.0.0
server.port=8080
